import type { Metadata } from "next";
import "./globals.css";
// 1. Apne Header component ko import karein
import Header from "@/components/home/Header";

export const metadata: Metadata = {
  title: "CarMilaap - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* 2. Body ke start mein Header laga dein */}
        <Header /> 
        
        {/* 3. Yeh aapke pages ka content hoga */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}